version: "3"
services:
  neo-scan:
    build: .
    image: neo-scan-neo-compiler:latest
    container_name: "neo-scan"
    ports:
      - 4000:4000
    links:
      - postgresql:postgres
      - neo-csharp-nodes:30333
      - neo-csharp-nodes:30334
      - neo-csharp-nodes:30335
      - neo-csharp-nodes:30336
      - neo-python-all-in-one:30337
      - neo-python-all-in-one:38088
  postgresql:
    image: postgres:10.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
  neo-python-all-in-one:
    image: neo-compiler-neo-python:latest
    container_name: "neo-python-all-in-one"  
    ports:
      - 30337:30337
      - 38088:38088
    links:
      - neo-csharp-nodes
  neo-csharp-nodes:
    image: neo-compiler-csharp-nodes:latest  
    container_name: "neo-csharp-nodes" 
    ports:
      - "20333:20333"
      - "20334:20334"
      - "20335:20335"
      - "20336:20336"
      - "30333:30333"
      - "30334:30334"
      - "30335:30335"
      - "30336:30336"
