version: "3"
services:
  eco-neo-csharp-nodes-running:
    image: eco-neo-csharp-nodes:2.7.4
    container_name: "eco-neo-csharp-nodes-running"
    ports:
      - "20333:20333"
      - "20334:20334"
      - "20335:20335"
      - "20336:20336"
      - "30333:30333"
      - "30334:30334"
      - "30335:30335"
      - "30336:30336"

  neo-scan-running:
    image: "registry.gitlab.com/cityofzion/neo-scan:22520645-master"
    container_name: "eco-neo-scan-running"
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      HOST: ${HOST_NAME}
      NEO_SEED_1: "http://${SEED_SERVER}:30333"
      NEO_SEED_2: "http://${SEED_SERVER}:30334"
      NEO_SEED_3: "http://${SEED_SERVER}:30335"
      NEO_SEED_4: "http://${SEED_SERVER}:30336"
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
    links:
      - eco-neoscan-postgresql-running:postgres
      - eco-neo-csharp-nodes-running:30333
      - eco-neo-csharp-nodes-running:30334
      - eco-neo-csharp-nodes-running:30335
      - eco-neo-csharp-nodes-running:30336
      - eco-neo-python-rest-running:8080
    depends_on:
      - eco-neoscan-postgresql-running
      - eco-neo-python-rest-running
      - eco-neo-csharp-nodes-running

#  notifications-server:
#    container_name: "notifications-server"
#    image: "cityofzion/neo-python"
#    depends_on:
#      - eco-neo-csharp-nodes-running
#    volumes:
#      - ./custom-config.json:/neo-python/custom-config.json
#    command: "/usr/bin/python3 /neo-python/neo/bin/api_server.py --config /neo-python/custom-config.json --port-rest 8090"
#    ports:
#      - 9000:8090

  eco-neoscan-postgresql-running:
    image: postgres:10.1
    container_name: "eco-neoscan-postgresql-running"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  eco-neo-python-rest-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-rest-running"
    ports:
      - "8080:8080"
      - "10332:10332"
    links:
      - eco-neo-csharp-nodes-running
    command: /bin/bash /opt/start_neopython_rpc_rest.sh
    depends_on:
      - eco-neo-csharp-nodes-running

  eco-neo-python-genesis-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-genesis-running"
    links:
      - eco-neo-csharp-nodes-running
    command: /bin/bash /opt/callGenesisBlockCreation.sh
    depends_on:
      - eco-neo-csharp-nodes-running

  eco-neo-python-w1-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-w1-running"
    environment:
      - PYTHON_WALLET=w1.wallet
      - PYTHON_NAME=pythonW1
      - PYTHON_PWD=coz
    links:
      - eco-neo-csharp-nodes-running
    command: /bin/bash /opt/callPythonInfinitySync.sh
    depends_on:
      - eco-neo-csharp-nodes-running

  eco-neo-python-w2-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-w2-running"
    environment:
      - PYTHON_WALLET=w2.wallet
      - PYTHON_NAME=pythonW2
      - PYTHON_PWD=coz
    links:
      - eco-neo-csharp-nodes-running
    command: /bin/bash /opt/callPythonInfinitySync.sh  #openPythonWallet.sh
    depends_on:
      - eco-neo-csharp-nodes-running

  eco-neo-python-logger-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-logger-running"
    links:
      - eco-neo-csharp-nodes-running
    command: /bin/bash /opt/callPythonLogger.sh  #openPythonWallet.sh
    depends_on:
      - eco-neo-csharp-nodes-running
